name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      # Create and activate virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install dependencies with specific versions for stability
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pelican==4.9.1'
          pip install 'markdown==3.5.2'
          pip install 'ghp-import==1.1.0'

      # Build the site
      - name: Build site
        run: |
          pelican content -s pelicanconf.py -o output

      # Deploy to GitHub Pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
